name: 'Deploy Azure Resources using Terraform'

on:
  workflow_dispatch:
    inputs:
      actions:
          type: choice
          description: 'Select an action to perform'
          options:
            - apply
            - destroy
          required: true
          default: apply
  push:
    branches: 
         - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check out to repo
        uses: actions/checkout@v2

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      # - name: Setting Terraform Variables
      #   run: |
      #     export TF_VAR_client_id=${{ secrets.AZURE_CLIENT_ID }}
      #     export TF_VAR_tenant_id=${{ secrets.AZURE_TENANT_ID }}
      #     export TF_VAR_sub_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      # - name: Terraform Validate
      #   run: terraform validate
      #   continue-on-error: false

      # - name: Terraform Format
      #   run: terraform fmt
      #   continue-on-error: true

      # - name: Terraform Plan
      #   run: terraform plan
      #   continue-on-error: false

      - name: Terraform Apply
        if: github.event.inputs.actions == 'apply' || github.event_name == 'push'
        run: |
          terraform plan -out main.tfplan
          terraform apply main.tfplan

      - name: Terraform Destroy
        if: github.event.inputs.actions == 'destroy'
        run: |
          terraform plan -destroy -out main.destroy.tfplan
          terraform destroy main.destroy.tfplan
